<html lang="en">
<head>
    <base href="{BASE_URL}">

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Instituto de Idiomas</title>
</head>
<body>


<nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom" style="background-color: #f6f6f6">
    <div class="container">
        <div class="navbar-brand">        
            <img src="https://www.nebrija.com/medios/actualidadnebrija/wp-content/uploads/sites/2/2020/04/lenguas-del-mundo-787x459.jpg" alt="Bootstrap" width="150" height="90">
        </div>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>home">Instituto de Idiomas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= BASE_URL ?>idiomas">Idiomas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= BASE_URL ?>profesores">Profesores</a>
                </li>
            </ul>

            <?php if ($this->user): ?>
                <span class= "navbar-text"><?= htmlspecialchars($this->user->email)?></span>
                <span class="navbar-text"><a class="nav-link" href="<?= BASE_URL ?>logout">Salir</a></span>
                <?php else :?>
                    <div>
                        <a href="<?= BASE_URL ?>showLogin" type='button' class= "btn btn-sm btn-outline-secondary">Iniciar Sesion</a>
                    </div>
            <?php endif ?>

        </div>
    </div>   
</nav>
