<?php if ($error): ?>       
<div class='alert alert-danger' role='alert'>
    <?= $error ?>
</div> 
<?php endif ?>

<?php require 'templates/layouts/header.phtml' ?>

<div class="container text-center my-4 h-100 d-flex flex-column" style="background-image:url(https://www.usergioarboleda.edu.co/wp-content/uploads/2017/03/ser_bilingues_2.jpg); background-size: contain;
background-repeat: no-repeat">
    <div class="row align-items-center justify-content-center">
        <div class="col"></div>
        <div class="col">
            <form method= 'post' action= 'login'>
            <div class ="row g-1 align-items-center">
                <div class = 'form-group'>
                        <label for= 'email'>Email</label>
                        <input type='email' class='form-control' id='email' name='email' required>
                </div>
            </div>
                <div class = 'form-group'>
                    <label for= 'password'>Password</label>
                    <input type='password' class='form-control' id='password' name='password' required>
                </div>
                <div class= "button my-2">
                    <button type='submit' class= "btn btn-primary">Login</button>
                </div>
            </form>
        </div>
        <div class="col"></div>
    </div>
</div>

<?php require 'templates/layouts/footer.phtml' ?>