<?php require 'templates/layouts/header.phtml' ?>

<div class="container text-center my-4 h-100 d-flex flex-column" style="background-image:url(https://www.usergioarboleda.edu.co/wp-content/uploads/2017/03/ser_bilingues_2.jpg); background-size: contain;
background-repeat: no-repeat">
    <div class="row align-items-center">
        <form action="" method="POST" enctype="multipart/form-data" class="my-4">
        <div class= "row">
            <div class="col-3"></div>
            <div class="col-4">
                <div class="form-group">
                    <label>Nombre</label>
                    <input required name="nombre" type="text" class="form-control" 
                    <?php if($idioma): ?> 
                        value="<?= htmlspecialchars($idioma->nombre) ?>"
                    <?php endif ?> >
                </div>
            </div>

            <div class="col-2">
                <div class="form-group">
                    <label>Modulos</label>
                    <select required name="modulos" class="form-control">
                        <option value="1" <?php if(($idioma) && ($idioma->modulos == 1)): ?>selected <?php endif?>>1</option>
                        <option value="2" <?php if(($idioma) && ($idioma->modulos == 2)): ?>selected <?php endif?>>2</option>
                        <option value="3" <?php if(($idioma) && ($idioma->modulos == 3)): ?>selected <?php endif?>>3</option>
                        <option value="4" <?php if(($idioma) && ($idioma->modulos == 4)): ?>selected <?php endif?>>4</option>
                    </select>
                </div>
            </div>
            <div class="col-3"></div>
        </div>
        <div class= "row">
            <div class="col-4"></div>
            <div class="col-4">
                <div class="form-group">
                    <?php if($idioma): ?> 
                        <img src="<?= BASE_URL.$idioma->imagen ?>"/>
                    <?php endif ?> 
                    <input type="file" name="input_name"/>                
                </div>
            </div>
            <div class="col-4"></div>
        </div>

        <div class= "row">
            <div class="col-3"></div>
                <div class="col-6">
                    <div class="form-group">
                        <label>Descripción</label>
                        <textarea name="descripcion" class="form-control" rows="3"><?php if($idioma): ?><?= htmlspecialchars($idioma->descripcion) ?><?php endif ?></textarea>
                    </div>
                </div>
            <div class="col-3"></div>
        </div>

        <div class= "button my-2">   
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
        </form>
    </div>
</div>

<?php require 'templates/layouts/footer.phtml' ?>