<?php require 'templates/layouts/header.phtml' ?>

<div class="container text-center my-4 d-flex flex-column" style="background-color: #f6f6f6">
    <div class="my-4 align-items-center justify-content-center high-auto">
        <div class= "row">
            <div class="col-5"></div>   
            <div class="col-5"></div>
            <div class="col-2">
                <div class= "button my-2">
                    <a href="<?= BASE_URL?>agregar/profesor" type='button' class='btn btn-success'>Agregar Profesor</a>
                </div>
            </div>
        </div>

        <ul class="list-group">
            <?php foreach($profesores as $profesor): ?>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <?php if ($profesor->imagen):?>
                        <img src="<?= BASE_URL.$profesor->imagen ?>"/>
                    <?php endif ?>
                    <div class="label">
                        <a href="<?= BASE_URL ?>profesor/<?= $profesor->id?>"><b><?= htmlspecialchars($profesor->nombre) ?></b></a> | <?=($indiceIdiomas[$profesor->id_idioma])?> | <?=($profesor->telefono)?> | <?= ($profesor->email) ?> 
                    </div>
                    <div class= "ml-auto">
                        <a href="<?= BASE_URL?>Modificar/profesor/<?= $profesor->id ?>" type='button' class='btn btn-secondary'>Modificar</a>
                        <a href="<?= BASE_URL?>eliminar/profesor/<?= $profesor->id ?>" type='button' class='btn btn-danger'>Eliminar</a>
                    </div> 
                
                </li>
            <?php endforeach ?>
        </ul>

    </div>
</div>

<?php require 'templates/layouts/footer.phtml' ?>
